CREATE TABLE IF NOT EXISTS test1 (
       Id INTEGER PRIMARY KEY AUTOINCREMENT,
       name TEXT
);

CREATE TABLE IF NOT EXISTS test2 (
       Id INTEGER PRIMARY KEY AUTOINCREMENT,
       name TEXT
);